---
# Deploy Galera using the role of directory
- name: Deploy Galera
  hosts: galera-cluster-nodes
  tasks:
    - name: Include ansible-mariadb-galera-cluster
      include_role:
        name: ansible-mariadb-galera-cluster

# Deploy HA and Keedalived using the main.yml file in directory
- name: Deploy HA and Keedalived
  hosts: haproxy
  tasks:
    - include: Haproxy_Keepalived/main.yml
