---
# About this playbook I have to say that it will set a galera database in 
# multiple places or you could say (Clusters) and it will configure it to
# be used for Haproxy and other things. 

# The way this clusters are configured is you must change some of the variables
# in the variables files to set passwords, host, port and etc. for the base configurations
# you just need to change the password, set the hosts in the inventory file, and use the main 
# playbook in the previous directory.
# Here are some examples of the files you need to change:
# hosts:
# [
#     [galera]
#     172.20.92.132
#     172.20.92.133
#     172.20.92.134
#     [galera-cluster-nodes]
#     172.20.92.132
#     172.20.92.133
#     172.20.92.134
# ]

- name: Deploy Galera
  hosts: galera-cluster-nodes
  tasks:
    - name: Include ansible-mariadb-galera-cluster
      include_role:
        name: ansible-mariadb-galera-cluster

- name: Deploy HA and Keedalived
  hosts: haproxy
  tasks:
    - include: Haproxy_Keepalived/main.yml
