---
- name: Deploy Galera
  hosts: galera-cluster-nodes
  tasks:
    - name: Include ansible-mariadb-galera-cluster
      include_role:
        name: ansible-mariadb-galera-cluster

- name: Deploy HA and Keedalived
  hosts: haproxy
  tasks:
    - include: Haproxy_Keepalived/main.yml
