---
- name: configure_root_access | configuring root my.cnf
  template:
    src: "root/my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: "root"
    group: "root"
    mode: "u=rw,g=,o="
  become: true
  no_log: true
  when: ansible_os_family == "RedHat"

- name: configure_root_access | updating root passwords
  mysql_user:
    host: "{{ item }}"
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
    name: "root"
    password: "{{ mariadb_mysql_root_password }}"
    priv: '*.*:ALL,GRANT'
  become: true
  no_log: true
  run_once: true
  retries: 6
  delay: 5
  with_items:
    # - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
    - '{{ mariadb_mysql_ha_hosts }}'
  tags:
    - updating_root_passwords

- name: configure_root_access | updating root passwords (allow from anywhere)
  mysql_user:
    # host: "{{ item }}"
    host: " {{ mariadb_mysql_ha_hosts }}"
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
    name: "root"
    password: "{{ mariadb_mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  become: true
  no_log: true
  run_once: true
  retries: 6
  delay: 5
  with_items:
    - '{{ mariadb_mysql_ha_hosts }}'
  when: galera_allow_root_from_any|bool
  tags:
    - updating_root_passwords
